import os
import requests
import logging
import markdown
from typing import List, Optional

logger = logging.getLogger(__name__)

def send_email(to_email: str, subject: str, html_content: Optional[str] = None, markdown_content: Optional[str] = None, to_name: Optional[str] = None) -> bool:
    """
    Send a transactional email using the Brevo (formerly Sendinblue) API.
    
    Args:
        to_email (str): The recipient's email address.
        subject (str): The subject of the email.
        html_content (str, optional): The HTML content of the email body.
        markdown_content (str, optional): The Markdown content to be converted to HTML.
        to_name (str, optional): The name of the recipient.
    
    Returns:
        bool: True if the email was sent successfully, False otherwise.
    """
    
    api_key = os.getenv("BREVO_API_KEY")
    sender_email = os.getenv("BREVO_SENDER_EMAIL")
    sender_name = os.getenv("BREVO_SENDER_NAME", "Weekend Planner Agent")

    if not api_key:
        logger.error("BREVO_API_KEY environment variable is not set. Cannot send email.")
        return False
        
    final_html = html_content
    
    if markdown_content:
        # Convert Markdown to HTML
        md_html = markdown.markdown(markdown_content, extensions=['extra', 'nl2br'])
        
        # Wrap in a nice template
        final_html = f"""
        <html>
        <head>
            <style>
                body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max_width: 800px; margin: 0 auto; padding: 20px; }}
                h1, h2, h3 {{ color: #2c3e50; margin-top: 1.5em; }}
                h1 {{ border-bottom: 2px solid #eee; padding-bottom: 10px; }}
                h2 {{ border-bottom: 1px solid #eee; padding-bottom: 5px; }}
                a {{ color: #3498db; text-decoration: none; }}
                a:hover {{ text-decoration: underline; }}
                code {{ background-color: #f8f9fa; padding: 2px 4px; border-radius: 4px; font-family: monospace; }}
                pre {{ background-color: #f8f9fa; padding: 15px; border-radius: 5px; overflow-x: auto; }}
                ul, ol {{ padding-left: 20px; }}
                li {{ margin-bottom: 5px; }}
                blockquote {{ border-left: 4px solid #ddd; padding-left: 15px; color: #666; margin: 15px 0; }}
                .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; font-size: 0.9em; color: #888; text-align: center; }}
            </style>
        </head>
        <body>
            {md_html}
            <div class="footer">
                <p>Generated by Weekend Planner Agent</p>
            </div>
        </body>
        </html>
        """

    if not final_html:
        logger.error("No content provided for email (neither html_content nor markdown_content).")
        return False

    url = "https://api.brevo.com/v3/smtp/email"
    headers = {
        "accept": "application/json",
        "api-key": api_key,
        "content-type": "application/json"
    }
    
    payload = {
        "sender": {
            "name": sender_name,
            "email": sender_email
        },
        "to": [
            {
                "email": to_email,
                "name": to_name or to_email.split("@")[0]
            }
        ],
        "subject": subject,
        "htmlContent": final_html
    }

    try:
        response = requests.post(url, json=payload, headers=headers, timeout=10)
        response.raise_for_status()
        logger.info(f"Email sent successfully to {to_email}. Message ID: {response.json().get('messageId')}")
        return True
    except requests.exceptions.RequestException as e:
        logger.error(f"Failed to send email to {to_email}: {e}")
        if e.response is not None:
             logger.error(f"Response content: {e.response.text}")
        return False